// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    first_name, last_name, email, phone, age, status
) VALUES (
             $1, $2, $3,$4, $5, $6
         )
RETURNING user_id, first_name, last_name, email, phone, age, status
`

type CreateUserParams struct {
	FirstName string
	LastName  string
	Email     string
	Phone     pgtype.Text
	Age       pgtype.Int4
	Status    interface{}
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Age,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Age,
		&i.Status,
	)
	return i, err
}

const deleteUserById = `-- name: DeleteUserById :exec
DELETE FROM users WHERE user_id = $1
`

func (q *Queries) DeleteUserById(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserById, userID)
	return err
}

const retrieveAllUsers = `-- name: RetrieveAllUsers :many
SELECT user_id, first_name, last_name, email, phone, age, status FROM users
`

func (q *Queries) RetrieveAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, retrieveAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.Age,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retrieveUserById = `-- name: RetrieveUserById :one
SELECT user_id, first_name, last_name, email, phone, age, status FROM users WHERE user_id = $1 LIMIT 1
`

func (q *Queries) RetrieveUserById(ctx context.Context, userID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, retrieveUserById, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Age,
		&i.Status,
	)
	return i, err
}

const updateUserById = `-- name: UpdateUserById :exec

UPDATE users
SET
    first_name = COALESCE($1, first_name),
    last_name  = COALESCE($2, last_name),
    email      = COALESCE($3, email),
    age        = COALESCE($4, age),
    phone      = COALESCE($5, phone),
    status     = COALESCE($6, status)
WHERE user_id = $7
RETURNING user_id, first_name, last_name, email, phone, age, status
`

type UpdateUserByIdParams struct {
	FirstName string
	LastName  string
	Email     string
	Age       pgtype.Int4
	Phone     pgtype.Text
	Status    interface{}
	UserID    pgtype.UUID
}

func (q *Queries) UpdateUserById(ctx context.Context, arg UpdateUserByIdParams) error {
	_, err := q.db.Exec(ctx, updateUserById,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Age,
		arg.Phone,
		arg.Status,
		arg.UserID,
	)
	return err
}
