version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bodyclose
    - decorder
    - dogsled
    - durationcheck
    - errname
    - errorlint
    - goconst
    - gocritic
    - gomoddirectives
    - goprintffuncname
    - gosec
    - importas
    - loggercheck
    - makezero
    - mirror
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - nosprintfhostport
    - promlinter
    - reassign
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - usestdlibvars
    - whitespace
formatters:
  enable:
    - gci
    - gofumpt
    - gofmt
output:
  formats:
    json :
      path: ./golangci-lint/report.json
    text:
      path: ./golangci-lint/report.txt
      print-linter-name: true
      print-issued-lines: true
      colors: true
severity:
  default: debug
run:
  fix: true